package sysgen

import (
	"context"
	"testing"
)

func TestOracleGeneratorProducesValidSystem(t *testing.T) {
	g := NewOracleGenerator()
	if !Oracle(g) {
		t.Fatal("expected Oracle(g) to be true")
	}

	sys, err := Generate(context.Background(), g, Brief{
		Name:        "Oracle System",
		Description: "A standard system generated by oracle",
	})
	if err != nil {
		t.Fatalf("Generate with OracleGenerator failed: %v", err)
	}

	if sys.Name != "Oracle System" {
		t.Fatalf("expected Name 'Oracle System', got %q", sys.Name)
	}
	if sys.Mechanics == nil {
		t.Fatal("expected Mechanics to be non-nil")
	}
	if len(sys.Mechanics.Stats) != 3 {
		t.Fatalf("expected 3 stats, got %d", len(sys.Mechanics.Stats))
	}
	if !sys.Verify.OK {
		t.Fatalf("expected Verify.OK to be true, got false (failures: %v)", sys.Verify.Failures)
	}
}
