package storage

import (
	"database/sql"
	"sync"

	"github.com/XSAM/otelsql"
	semconv "go.opentelemetry.io/otel/semconv/v1.37.0"
)

// otelsql wraps the modernc.org/sqlite driver once, so every QueryContext and
// ExecContext becomes a span without changing any storage call. The wrapped
// name is generated by otelsql and cached here.
var (
	registerDriverOnce sync.Once
	otelDriverName     string
	registerDriverErr  error
)

// otelDriverNameFor returns the registered name of the instrumented driver,
// registering it on first use.
func otelDriverNameFor() (string, error) {
	registerDriverOnce.Do(func() {
		otelDriverName, registerDriverErr = otelsql.Register("sqlite",
			otelsql.WithAttributes(semconv.DBSystemNameSQLite),
			otelsql.WithSpanOptions(otelsql.SpanOptions{OmitRows: true}),
		)
	})
	return otelDriverName, registerDriverErr
}

// openWrapped opens the game database through the instrumented driver.
func openWrapped(path, pragmas string) (*sql.DB, error) {
	name, err := otelDriverNameFor()
	if err != nil {
		return nil, err
	}
	return sql.Open(name, "file:"+path+"?"+pragmas)
}
